# Generated by Django 4.2.9 on 2024-02-16 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('index_logo', models.ImageField(upload_to='brands/titles/%Y/%m/%d')),
                ('brand_logo', models.ImageField(upload_to='brands/titles/%Y/%m/%d')),
                ('image', models.ImageField(upload_to='brands/images/%Y/%m/%d')),
                ('brand_text_color', models.CharField(choices=[('white', 'white'), ('black', 'black')], max_length=5)),
                ('show_text_color', models.CharField(choices=[('white', 'white'), ('black', 'black')], max_length=5)),
                ('image_show', models.ImageField(upload_to='brands/shows/%Y/%m/%d')),
                ('youtube_channel', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='modelImages/%Y/%m/%d')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo1', models.ImageField(upload_to='models/photos/%Y/%m/%d')),
                ('photo2', models.ImageField(upload_to='models/photos/%Y/%m/%d')),
                ('biography1', models.TextField()),
                ('biography2', models.TextField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo1', models.ImageField(upload_to='models/photos/%Y/%m/%d')),
                ('photo2', models.ImageField(upload_to='models/photos/%Y/%m/%d')),
                ('biography1', models.TextField()),
                ('biography2', models.TextField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
