# Generated by Django 4.2 on 2023-12-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name_image',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_logo',
            field=models.ImageField(null=True, upload_to='brands/titles/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='brand',
            name='index_logo',
            field=models.ImageField(null=True, upload_to='brands/titles/%Y/%m/%d'),
        ),
    ]
