# Generated by Django 4.2 on 2023-12-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_brand_name_image_brand_brand_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_text_color',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black')], max_length=15, null=True),
        ),
    ]
