# Generated by Django 4.2 on 2023-12-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_brand_brand_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer',
            name='photo1',
            field=models.ImageField(upload_to='models/photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='photo2',
            field=models.ImageField(upload_to='models/photos/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='modelImages/%Y/%m/%d')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
            ],
        ),
    ]
