# Generated by Django 4.2 on 2023-12-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_designer_photo1_alter_designer_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image_show',
            field=models.ImageField(null=True, upload_to='brands/shows/%Y/%m/%d'),
        ),
    ]
