# Generated by Django 4.2 on 2023-12-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_showlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show_text_color',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black')], max_length=15, null=True),
        ),
    ]
